CREATE TABLE IF NOT EXISTS usuarios (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  correo VARCHAR(150) NOT NULL UNIQUE,
  telefono VARCHAR(30),
  password_hash VARCHAR(255) NOT NULL,
  rol ENUM('Administrador', 'Usuario') NOT NULL DEFAULT 'Usuario',
  estado ENUM('Activo', 'Inactivo') NOT NULL DEFAULT 'Activo',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS catalogo_estado_reserva (
  id TINYINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS catalogo_tipo_alerta (
  id TINYINT UNSIGNED PRIMARY KEY,
  nombre VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS parqueos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(150) NOT NULL,
  provincia VARCHAR(80) NOT NULL,
  zona VARCHAR(100) NOT NULL,
  ubicacion VARCHAR(255) NOT NULL,
  precio DECIMAL(10,2) NOT NULL,
  espacios INT UNSIGNED NOT NULL DEFAULT 0,
  calificacion DECIMAL(3,2) NOT NULL DEFAULT 0,
  disponible TINYINT(1) NOT NULL DEFAULT 1,
  imagen VARCHAR(500),
  origen ENUM('base', 'aprobado') NOT NULL DEFAULT 'base',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS reservas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  external_id VARCHAR(60) UNIQUE,
  usuario VARCHAR(120) NOT NULL,
  placa VARCHAR(20) NOT NULL,
  parqueo VARCHAR(150) NOT NULL,
  espacio VARCHAR(25) NOT NULL,
  fecha DATE NOT NULL,
  hora TIME NOT NULL,
  hora_salida TIME NOT NULL,
  estado ENUM('Activa', 'Confirmada', 'Cancelada') NOT NULL DEFAULT 'Activa',
  monto DECIMAL(10,2) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS espacios (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  parqueo_id BIGINT UNSIGNED NOT NULL,
  codigo VARCHAR(25) NOT NULL,
  zona VARCHAR(40) NOT NULL,
  estado ENUM('Disponible', 'Ocupado', 'Reservado', 'Mantenimiento') NOT NULL DEFAULT 'Disponible',
  tarifa DECIMAL(10,2) NOT NULL DEFAULT 0,
  placa VARCHAR(20) DEFAULT '-',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  UNIQUE KEY uq_espacio_parqueo_codigo (parqueo_id, codigo),
  CONSTRAINT fk_espacios_parqueo FOREIGN KEY (parqueo_id) REFERENCES parqueos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS favoritos (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NOT NULL,
  parqueo_id BIGINT UNSIGNED NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uq_favorito_usuario_parqueo (usuario_id, parqueo_id),
  CONSTRAINT fk_favoritos_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE CASCADE,
  CONSTRAINT fk_favoritos_parqueo FOREIGN KEY (parqueo_id) REFERENCES parqueos(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS app_state (
  state_key VARCHAR(120) PRIMARY KEY,
  state_value JSON NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS alertas (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  usuario_id BIGINT UNSIGNED NULL,
  tipo_alerta_id TINYINT UNSIGNED NOT NULL,
  titulo VARCHAR(120) NOT NULL,
  mensaje TEXT NOT NULL,
  referencia VARCHAR(80) DEFAULT NULL,
  leida TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_alertas_usuario FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  CONSTRAINT fk_alertas_tipo FOREIGN KEY (tipo_alerta_id) REFERENCES catalogo_tipo_alerta(id)
);
